services:
    nginx:
        image: nginx
        container_name: nginx
        build: ./requirements/nginx
        ports:
            - "443:443"
        depends_on:
            - wordpress
        volumes:
            -wp_files:/var/www/html
        networks:
            - inception_network
        restart: always
    wordpress:
        image: wordpress
        container_name: wordpress
        build: ./requirements/wordpress
        ports:
            - "80:80"
        depends_on:
            - mariadb
        volumes:
            - wp_files:/var/www/html
            - wp_DB:/var/lib/mysql
        networks:
            - inception_network
        restart: always

    mariadb:
        image: mariadb
        container_name: mariadb
        build: ./requirements/mariadb
        ports:
            - "3306:3306"
        restart: always

networks:
    inception_network:
        driver: bridge

volumes:
    wp_DB:
        device: /home/soel-bou/data/wp_DB
    wp_files:
        device: /home/soel-bou/data/wp_files