services:
  mariadb:
    image: mariadb:soel
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - wp_DB:/var/lib/mysql
    networks:
      - inception_network
    env_file: .env
    environment:
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    # Optional: Enable if needed
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10
    restart: always

  nginx:
    image: nginx:soel
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "8443:8443"
    depends_on:
      - wordpress
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception_network
    env_file: .env
    restart: always

  wordpress:
    image: wordpress:soel
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception_network
    env_file: .env
    environment:
      MARIADB_DATABASE: ${SQL_DATABASE}
      MARIADB_USER: ${SQL_USER}
      MARIADB_PASSWORD: ${SQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USERNAME: ${WP_USERNAME}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_ROLE: ${WP_USER_ROLE}
    restart: always

networks:
  inception_network:
    driver: bridge

volumes:
  wp_DB:
    driver_opts:
      type: none
      o: bind
      device: /home/soel-bou/data/wp_DB
  wp_files:
    driver_opts:
      type: none
      o: bind
      device: /home/soel-bou/data/wp_files
  # new:
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /goinfre/soel-bou/data/wp2
